#[path = "../01_values_and_comparison/01_truthiness/rust/test_01_core.rs"]
mod concept_01_values_and_comparison_01_truthiness_01_core;
#[path = "../01_values_and_comparison/02_equality/rust/test_01_core.rs"]
mod concept_01_values_and_comparison_02_equality_01_core;
#[path = "../01_values_and_comparison/03_numeric_models_and_conversion/rust/test_01_core.rs"]
mod concept_01_values_and_comparison_03_numeric_models_and_conversion_01_core;
#[path = "../01_values_and_comparison/04_null_missing_and_optional_values/rust/test_01_core.rs"]
mod concept_01_values_and_comparison_04_null_missing_and_optional_values_01_core;
#[path = "../01_values_and_comparison/05_identity_aliasing_and_copying/rust/test_01_core.rs"]
mod concept_01_values_and_comparison_05_identity_aliasing_and_copying_01_core;
#[path = "../01_values_and_comparison/06_ordering_hashing_and_key_semantics/rust/test_01_core.rs"]
mod concept_01_values_and_comparison_06_ordering_hashing_and_key_semantics_01_core;
#[path = "../02_functions_and_calls/01_argument_passing/rust/test_01_core.rs"]
mod concept_02_functions_and_calls_01_argument_passing_01_core;
#[path = "../02_functions_and_calls/02_scope_name_lookup_and_shadowing/rust/test_01_core.rs"]
mod concept_02_functions_and_calls_02_scope_name_lookup_and_shadowing_01_core;
#[path = "../02_functions_and_calls/03_closures_capture_and_lifetime/rust/test_01_core.rs"]
mod concept_02_functions_and_calls_03_closures_capture_and_lifetime_01_core;
#[path = "../02_functions_and_calls/04_callable_binding_and_invocation_context/rust/test_01_core.rs"]
mod concept_02_functions_and_calls_04_callable_binding_and_invocation_context_01_core;
#[path = "../02_functions_and_calls/05_callable_adaptation_and_partial_application/rust/test_01_core.rs"]
mod concept_02_functions_and_calls_05_callable_adaptation_and_partial_application_01_core;
#[path = "../03_errors_and_resources/01_resource_cleanup/rust/test_01_core.rs"]
mod concept_03_errors_and_resources_01_resource_cleanup_01_core;
#[path = "../03_errors_and_resources/01_resource_cleanup/rust/test_02_partial_acquisition_and_control_flow.rs"]
mod concept_03_errors_and_resources_01_resource_cleanup_02_partial_acquisition_and_control_flow;
#[path = "../03_errors_and_resources/02_exception_propagation_and_matching/rust/test_01_core.rs"]
mod concept_03_errors_and_resources_02_exception_propagation_and_matching_01_core;
#[path = "../03_errors_and_resources/02_exception_propagation_and_matching/rust/test_02_rethrow_and_completion_precedence.rs"]
mod concept_03_errors_and_resources_02_exception_propagation_and_matching_02_rethrow_and_completion_precedence;
#[path = "../03_errors_and_resources/03_error_chaining_suppression_and_aggregation/rust/test_01_core.rs"]
mod concept_03_errors_and_resources_03_error_chaining_suppression_and_aggregation_01_core;
#[path = "../03_errors_and_resources/03_error_chaining_suppression_and_aggregation/rust/test_02_multiple_cleanup_failures.rs"]
mod concept_03_errors_and_resources_03_error_chaining_suppression_and_aggregation_02_multiple_cleanup_failures;
#[path = "../03_errors_and_resources/04_contracts_assertions_and_failure_signaling/rust/test_01_core.rs"]
mod concept_03_errors_and_resources_04_contracts_assertions_and_failure_signaling_01_core;
#[path = "../03_errors_and_resources/04_contracts_assertions_and_failure_signaling/rust/test_02_configuration_and_runtime_boundaries.rs"]
mod concept_03_errors_and_resources_04_contracts_assertions_and_failure_signaling_02_configuration_and_runtime_boundaries;
#[path = "../04_collections_and_iteration/01_iteration_protocol/rust/test_01_core.rs"]
mod concept_04_collections_and_iteration_01_iteration_protocol_01_core;
#[path = "../04_collections_and_iteration/01_iteration_protocol/rust/test_02_iterable_iterator_and_fallbacks.rs"]
mod concept_04_collections_and_iteration_01_iteration_protocol_02_iterable_iterator_and_fallbacks;
#[path = "../04_collections_and_iteration/02_indexing_slicing_and_bounds/rust/test_01_core.rs"]
mod concept_04_collections_and_iteration_02_indexing_slicing_and_bounds_01_core;
#[path = "../04_collections_and_iteration/03_sequence_mutation_and_invalidation/rust/test_01_core.rs"]
mod concept_04_collections_and_iteration_03_sequence_mutation_and_invalidation_01_core;
#[path = "../04_collections_and_iteration/03_sequence_mutation_and_invalidation/rust/test_02_views_and_structural_changes.rs"]
mod concept_04_collections_and_iteration_03_sequence_mutation_and_invalidation_02_views_and_structural_changes;
#[path = "../04_collections_and_iteration/04_mapping_lookup_and_missing_keys/rust/test_01_core.rs"]
mod concept_04_collections_and_iteration_04_mapping_lookup_and_missing_keys_01_core;
#[path = "../04_collections_and_iteration/05_sets_membership_and_deduplication/rust/test_01_core.rs"]
mod concept_04_collections_and_iteration_05_sets_membership_and_deduplication_01_core;
#[path = "../04_collections_and_iteration/06_generators_laziness_and_early_termination/rust/test_01_core.rs"]
mod concept_04_collections_and_iteration_06_generators_laziness_and_early_termination_01_core;
#[path = "../04_collections_and_iteration/06_generators_laziness_and_early_termination/rust/test_02_closing_and_delegation.rs"]
mod concept_04_collections_and_iteration_06_generators_laziness_and_early_termination_02_closing_and_delegation;
#[path = "../04_collections_and_iteration/07_sorting_stability_and_custom_order/rust/test_01_core.rs"]
mod concept_04_collections_and_iteration_07_sorting_stability_and_custom_order_01_core;
#[path = "../04_collections_and_iteration/07_sorting_stability_and_custom_order/rust/test_02_key_failures_and_comparator_contracts.rs"]
mod concept_04_collections_and_iteration_07_sorting_stability_and_custom_order_02_key_failures_and_comparator_contracts;
#[path = "../05_objects_and_dispatch/01_construction_initialization_and_lifetime/rust/test_01_core.rs"]
mod concept_05_objects_and_dispatch_01_construction_initialization_and_lifetime_01_core;
#[path = "../05_objects_and_dispatch/02_member_attribute_lookup_and_properties/rust/test_01_core.rs"]
mod concept_05_objects_and_dispatch_02_member_attribute_lookup_and_properties_01_core;
#[path = "../05_objects_and_dispatch/03_inheritance_dynamic_dispatch_and_super/rust/test_01_core.rs"]
mod concept_05_objects_and_dispatch_03_inheritance_dynamic_dispatch_and_super_01_core;
#[path = "../05_objects_and_dispatch/04_encapsulation_private_state_and_immutability/rust/test_01_core.rs"]
mod concept_05_objects_and_dispatch_04_encapsulation_private_state_and_immutability_01_core;
#[path = "../05_objects_and_dispatch/05_operator_and_protocol_customization/rust/test_01_core.rs"]
mod concept_05_objects_and_dispatch_05_operator_and_protocol_customization_01_core;
#[path = "../05_objects_and_dispatch/06_introspection_reflection_and_runtime_type/rust/test_01_core.rs"]
mod concept_05_objects_and_dispatch_06_introspection_reflection_and_runtime_type_01_core;
#[path = "../06_text_binary_and_serialization/01_unicode_strings_and_code_units/rust/test_01_core.rs"]
mod concept_06_text_binary_and_serialization_01_unicode_strings_and_code_units_01_core;
#[path = "../06_text_binary_and_serialization/01_unicode_strings_and_code_units/rust/test_02_normalization_and_invalid_encoding.rs"]
mod concept_06_text_binary_and_serialization_01_unicode_strings_and_code_units_02_normalization_and_invalid_encoding;
#[path = "../06_text_binary_and_serialization/02_formatting_parsing_and_interpolation/rust/test_01_core.rs"]
mod concept_06_text_binary_and_serialization_02_formatting_parsing_and_interpolation_01_core;
#[path = "../06_text_binary_and_serialization/03_regular_expressions_and_state/rust/test_01_core.rs"]
mod concept_06_text_binary_and_serialization_03_regular_expressions_and_state_01_core;
#[path = "../06_text_binary_and_serialization/03_regular_expressions_and_state/rust/test_02_zero_width_and_failure_boundaries.rs"]
mod concept_06_text_binary_and_serialization_03_regular_expressions_and_state_02_zero_width_and_failure_boundaries;
#[path = "../06_text_binary_and_serialization/04_binary_buffers_views_and_endianness/rust/test_01_core.rs"]
mod concept_06_text_binary_and_serialization_04_binary_buffers_views_and_endianness_01_core;
#[path = "../06_text_binary_and_serialization/04_binary_buffers_views_and_endianness/rust/test_02_alignment_and_lifetime.rs"]
mod concept_06_text_binary_and_serialization_04_binary_buffers_views_and_endianness_02_alignment_and_lifetime;
#[path = "../06_text_binary_and_serialization/05_serialization_clone_and_transfer/rust/test_01_core.rs"]
mod concept_06_text_binary_and_serialization_05_serialization_clone_and_transfer_01_core;
#[path = "../06_text_binary_and_serialization/05_serialization_clone_and_transfer/rust/test_02_numeric_and_trust_boundaries.rs"]
mod concept_06_text_binary_and_serialization_05_serialization_clone_and_transfer_02_numeric_and_trust_boundaries;
